// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _geometry_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcppPoint
void rcppPoint();
RcppExport SEXP _geometry_rcppPoint() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcppPoint();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geometry_rcpp_hello_world", (DL_FUNC) &_geometry_rcpp_hello_world, 0},
    {"_geometry_rcppPoint", (DL_FUNC) &_geometry_rcppPoint, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_geometry(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
