// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test
void test(Rcpp::NumericVector obj);
RcppExport SEXP _mapboxGeometry_test(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type obj(objSEXP);
    test(obj);
    return R_NilValue;
END_RCPP
}
// rcpp_wrap_test
SEXP rcpp_wrap_test();
RcppExport SEXP _mapboxGeometry_rcpp_wrap_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_wrap_test());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mapboxGeometry_test", (DL_FUNC) &_mapboxGeometry_test, 1},
    {"_mapboxGeometry_rcpp_wrap_test", (DL_FUNC) &_mapboxGeometry_rcpp_wrap_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mapboxGeometry(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
