# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(obj) {
    invisible(.Call('_mapboxGeometry_test', PACKAGE = 'mapboxGeometry', obj))
}

rcpp_wrap_test <- function() {
    .Call('_mapboxGeometry_rcpp_wrap_test', PACKAGE = 'mapboxGeometry')
}

