# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_wrap_test <- function() {
    .Call('_mapboxGeometry_rcpp_wrap_test', PACKAGE = 'mapboxGeometry')
}

rcpp_as_test <- function() {
    .Call('_mapboxGeometry_rcpp_as_test', PACKAGE = 'mapboxGeometry')
}

rcpp_test_performance <- function(x) {
    .Call('_mapboxGeometry_rcpp_test_performance', PACKAGE = 'mapboxGeometry', x)
}

